spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/SpringBootLearning
        username: Alex
        password: AlexAlex
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate.ddl-auto: none
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
        enabled: false

